### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by gour** [bjhamilton/sublime_zk#1]
**Describe the bug**

Creating a new note does not seem to work properly.

**To Reproduce**
1. Command -Pallete: Create new Note'
2. typing note title at the bottom of the screen
3. get the console output as below...

**Expected behavior**
I expect to get a new not created, with a `tags = ` line etc.

**Console output**

```
Sublime_ZK: Using ag!
reloading settings Packages/sublime_zk/sublime_zk.sublime-settings
reloading settings Packages/sublime_zk/sublime_zk_results.sublime-settings
reloading settings Packages/sublime_zk/sublime_zk_search.sublime-settings
generating syntax summary
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/home/gour/.config/sublime-text-3/Packages/sublime_zk/sublime_zk.py", line 1907, in on_done
    if len(os.path.dirname(self.window.active_view().file_name()).split('/')[1:]) > \
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Desktop (please complete the following information):**
 - OS: Linux
 - ST version: 3.2.2 (build #3211)

**Comment by bjhamilton** [comment]
@gour This does not happen for me and I'm using the same code as you. My first thought is this error is caused probably due to your directory structure. So can you manually open sublime_zk.py and place the following code immediately after line 1906:

```python
    print(os.path.dirname(self.window.active_view().file_name()))
    print(os.path.dirname(self.window.active_view().file_name()).split('/'))
    print(os.path.dirname(self.window.active_view().file_name()).split('/')[1:])
```

**Comment by gour** [comment]
@bjhamilton Hmm, I get the following:

```
Traceback (most recent call last):
  File "/home/gour/.config/sublime-text-3/Packages/sublime_zk/sublime_zk.py", line 1907, in on_done
    print(os.path.dirname(self.window.active_view().file_name()))
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by bjhamilton** [comment]
Did you configure your project directory? What is your directory structure?

Did you follow any of the steps at **How do I create a project in SublimeText? > Manual approach** ?

**Comment by gour** [comment]
> Did you configure your project directory? What is your directory structure?
> 
> Did you follow any of [these](https://github.com/bjhamilton/sublime_zk#manual-approach) steps?

OK, started from the scratch and used 'Automatic' approach and now it seems that it works!! :-)

Now, just wonder if/how it is possible to enlarge font? The usual ST mechanism does not work?

**Comment by bjhamilton** [comment]
That's a ST specific question relating to the use of ST. You could try Ctrl and '+'. Otherwise there may be some info in the ST documentation for you.
